/**
 * Auto-generated by `mcp__supabase__generate_typescript_types`.
 * Regenerate after any schema migration — do not hand-edit.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      airlines: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          logo_url: string | null
          name: string
          sort_order: number
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          logo_url?: string | null
          name: string
          sort_order?: number
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          logo_url?: string | null
          name?: string
          sort_order?: number
        }
        Relationships: []
      }
      bookings: {
        Row: {
          adults: number
          child_no_bed: number
          children: number
          created_at: string
          id: string
          infants: number
          name: string | null
          package_id: string | null
          phone: string | null
          reference: string
          room_type: string | null
          status: string
          total_pkr: number
          unit_price: number | null
        }
        Insert: {
          adults?: number
          child_no_bed?: number
          children?: number
          created_at?: string
          id?: string
          infants?: number
          name?: string | null
          package_id?: string | null
          phone?: string | null
          reference: string
          room_type?: string | null
          status?: string
          total_pkr?: number
          unit_price?: number | null
        }
        Update: {
          adults?: number
          child_no_bed?: number
          children?: number
          created_at?: string
          id?: string
          infants?: number
          name?: string | null
          package_id?: string | null
          phone?: string | null
          reference?: string
          room_type?: string | null
          status?: string
          total_pkr?: number
          unit_price?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "bookings_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "packages"
            referencedColumns: ["id"]
          },
        ]
      }
      cities: {
        Row: {
          code: string
          created_at: string
          id: string
          is_active: boolean
          name: string
          sort_order: number
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          is_active?: boolean
          name: string
          sort_order?: number
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          is_active?: boolean
          name?: string
          sort_order?: number
        }
        Relationships: []
      }
      contacts: {
        Row: {
          created_at: string
          email: string | null
          id: string
          message: string
          name: string
          phone: string | null
        }
        Insert: {
          created_at?: string
          email?: string | null
          id?: string
          message: string
          name: string
          phone?: string | null
        }
        Update: {
          created_at?: string
          email?: string | null
          id?: string
          message?: string
          name?: string
          phone?: string | null
        }
        Relationships: []
      }
      hotels: {
        Row: {
          city: string
          created_at: string
          distance: string
          has_image: boolean
          id: string
          image_url: string | null
          location: string
          name: string
          rate_double: number
          rate_quad: number
          rate_sharing: number | null
          rate_triple: number
        }
        Insert: {
          city: string
          created_at?: string
          distance: string
          has_image?: boolean
          id?: string
          image_url?: string | null
          location: string
          name: string
          rate_double: number
          rate_quad: number
          rate_sharing?: number | null
          rate_triple: number
        }
        Update: {
          city?: string
          created_at?: string
          distance?: string
          has_image?: boolean
          id?: string
          image_url?: string | null
          location?: string
          name?: string
          rate_double?: number
          rate_quad?: number
          rate_sharing?: number | null
          rate_triple?: number
        }
        Relationships: []
      }
      packages: {
        Row: {
          airline: string
          baggage: string | null
          created_at: string
          departure_city: string
          departure_city_code: string
          departure_date: string
          duration_days: number
          featured: boolean
          flight_arrival_date: string | null
          flight_arrival_time: string | null
          flight_departure_date: string | null
          flight_departure_time: string | null
          flight_inbound_no: string | null
          flight_outbound_no: string | null
          flight_route: string | null
          group_code: string | null
          id: string
          is_published: boolean
          madinah_hotel_id: string | null
          madinah_nights: number
          makkah_hotel_id: string | null
          makkah_nights: number
          package_code: string | null
          price_child_no_bed: number | null
          price_double: number | null
          price_infant: number | null
          price_pkr: number
          price_quad: number | null
          price_sharing: number | null
          price_triple: number | null
          room_type: string | null
          room_types: string[]
          seats_available: number
          seats_total: number
          title: string
          updated_at: string
        }
        Insert: {
          airline: string
          baggage?: string | null
          created_at?: string
          departure_city: string
          departure_city_code: string
          departure_date: string
          duration_days: number
          featured?: boolean
          flight_arrival_date?: string | null
          flight_arrival_time?: string | null
          flight_departure_date?: string | null
          flight_departure_time?: string | null
          flight_inbound_no?: string | null
          flight_outbound_no?: string | null
          flight_route?: string | null
          group_code?: string | null
          id?: string
          is_published?: boolean
          madinah_hotel_id?: string | null
          madinah_nights?: number
          makkah_hotel_id?: string | null
          makkah_nights?: number
          package_code?: string | null
          price_child_no_bed?: number | null
          price_double?: number | null
          price_infant?: number | null
          price_pkr: number
          price_quad?: number | null
          price_sharing?: number | null
          price_triple?: number | null
          room_type?: string | null
          room_types?: string[]
          seats_available: number
          seats_total: number
          title: string
          updated_at?: string
        }
        Update: {
          airline?: string
          baggage?: string | null
          created_at?: string
          departure_city?: string
          departure_city_code?: string
          departure_date?: string
          duration_days?: number
          featured?: boolean
          flight_arrival_date?: string | null
          flight_arrival_time?: string | null
          flight_departure_date?: string | null
          flight_departure_time?: string | null
          flight_inbound_no?: string | null
          flight_outbound_no?: string | null
          flight_route?: string | null
          group_code?: string | null
          id?: string
          is_published?: boolean
          madinah_hotel_id?: string | null
          madinah_nights?: number
          makkah_hotel_id?: string | null
          makkah_nights?: number
          package_code?: string | null
          price_child_no_bed?: number | null
          price_double?: number | null
          price_infant?: number | null
          price_pkr?: number
          price_quad?: number | null
          price_sharing?: number | null
          price_triple?: number | null
          room_type?: string | null
          room_types?: string[]
          seats_available?: number
          seats_total?: number
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "packages_madinah_hotel_id_fkey"
            columns: ["madinah_hotel_id"]
            isOneToOne: false
            referencedRelation: "hotels"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "packages_makkah_hotel_id_fkey"
            columns: ["makkah_hotel_id"]
            isOneToOne: false
            referencedRelation: "hotels"
            referencedColumns: ["id"]
          },
        ]
      }
      testimonials: {
        Row: {
          created_at: string
          id: string
          name: string
          quote: string
          rating: number
          testimonial_date: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          quote: string
          rating: number
          testimonial_date: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          quote?: string
          rating?: number
          testimonial_date?: string
        }
        Relationships: []
      }
      transport_rates: {
        Row: {
          category: string
          created_at: string
          id: string
          price_car: number | null
          price_coaster: number | null
          price_gmc: number | null
          price_hiace: number | null
          price_staria: number | null
          route_from: string
          route_to: string
        }
        Insert: {
          category: string
          created_at?: string
          id?: string
          price_car?: number | null
          price_coaster?: number | null
          price_gmc?: number | null
          price_hiace?: number | null
          price_staria?: number | null
          route_from: string
          route_to: string
        }
        Update: {
          category?: string
          created_at?: string
          id?: string
          price_car?: number | null
          price_coaster?: number | null
          price_gmc?: number | null
          price_hiace?: number | null
          price_staria?: number | null
          route_from?: string
          route_to?: string
        }
        Relationships: []
      }
      visas: {
        Row: {
          country: string
          created_at: string
          id: string
          mode: string
          note: string | null
          price_pkr: number
          processing_days: number
          title: string
          type: string
          validity_days: number
        }
        Insert: {
          country: string
          created_at?: string
          id?: string
          mode: string
          note?: string | null
          price_pkr: number
          processing_days: number
          title: string
          type: string
          validity_days: number
        }
        Update: {
          country?: string
          created_at?: string
          id?: string
          mode?: string
          note?: string | null
          price_pkr?: number
          processing_days?: number
          title?: string
          type?: string
          validity_days?: number
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_admin: { Args: never; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
